const originalCategories = [

// LIST 1
"A boy’s name", 
"US cities",
"Things that are cold",
"School supplies",
"Pro sports teams",
"Insects",
"Breakfast Foods",
"Furniture",
"TV Shows",
"Things found in the ocean",
"Presidents",
"Product names",

// LIST 2
"Vegetables",
"States",
"Things you throw away",
"Occupations",
"Appliances",
"Cartoon Characters",
"Types of Drink",
"Musical Groups",
"Store Names",
"Things at a football game",
"Trees",
"Personality Traits",

// LIST 3 
"Articles of Clothing",
"Desserts",
"Car Parts",
"Things found on a map",
"Athletes",
"4-letter words",
"Items in a refrigerator",
"Farm animals",
"Street Names",
"Things at the beach",
"Colors",
"Tools",

// LIST 4
"Sports",
"Song Titles",
"Parts of the body",
"Ethnic foods",
"Things you shout",
"Birds",
"A girl’s name",
"Ways to get there from here",
"Items in a kitchen",
"Villians/monsters",
"Flowers",
"Things you replace",

// LIST 5 
"Sandwiches",
"Items in a catalog",
"World Leaders/politicians",
"School subjects",
"Excuses for being late",
"Ice cream flavors",
"Things that jump/bounce",
"Television stars",
"Things in a park",
"Foreign cities",
"Stones/gems",
"Musical instruments",

// LIST 6
"Things that are sticky",
"Awards/ceremonies",
"Cars",
"Spices/herbs",
"Bad habits",
"Cosmetics/toiletries",
"Celebrities",
"Cooking Utensils",
"Reptiles/amphibians",
"Parks",
"Leisure activities",
"Things you are allergic to",

// LIST 7 
"Fictional characters",
"Menu items",
"Magazines",
"Capitals",
"Kinds of candy",
"Items you save up to buy",
"Footwear",
"Something you keep hidden",
"Items in a suitcase",
"Things with tails",
"Sports equipment",
"Crimes",

// LIST 8
"Nicknames",
"Things in the sky",
"Pizza toppings",
"Colleges/universities",
"Fish",
"Countries",
"Things that have spots",
"Historical Figures",
"Something you’re afraid of",
"Terms of measurement",
"Items in this room",
"Book titles",

// LIST 9 
"Restaurants",
"Notorious people",
"Fruits",
"Things in the medicine cabinet",
"Toys",
"Household chores",
"Bodies of water",
"Authors",
"Halloween costumes",
"Weapons",
"Things that are round",
"Words associated with exercise",

// LIST 10
"Heroes",
"Gifts/presents",
"Terms of endearment",
"Kinds of dances",
"Things that are black",
"Vehicles",
"Tropical locations",
"College majors",
"Dairy Products",
"Things in a souvenir shop",
"Items in a purse/wallet",
"World records",

// LIST 11 
"Baby foods",
"Famous duos and trios",
"Things found in a desk",
"Vacation spots",
"Diseases",
"Words associated with money",
"Items in a vending machine",
"Movie titles",
"Games",
"Things that you wear",
"Beverages",
"Things at a circus",

// LIST 12
"Famous females",
"Medicine",
"Things made of metal",
"Hobbies",
"People in uniform",
"Things you plug in",
"Animals",
"Languages",
"Names",
"Junk food",
"Things that grow",
"Companies"
];

const moreCategories = [
"Things that have buttons",
"Fears",
"Things with wheels",
"Something that is green",
"Something to do at a party",
"A board game",
"Party themes",

""];

module.exports = {
    originalCategories,
    moreCategories
};